# Generated by Django 2.2.7 on 2019-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images')),
                ('status', models.BooleanField(default=False)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_up', models.DateField(auto_now=True)),
            ],
        ),
    ]
