# Generated by Django 2.2.7 on 2019-11-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='status',
            new_name='statut',
        ),
    ]
